services:
  backend:
    build: .
    container_name: fullstack-backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      BE_PORT: ${BE_PORT}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
