name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  ACR_NAME: giangpublicacr01           
  IMAGE_NAME: fullstack-backend        
  IMAGE_TAG: latest      

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Container Registry login
        shell: bash

        env: 
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo "Logging into Azure Container Registry: $ACR_NAME"
          docker login "$ACR_NAME.azurecr.io" --username "$acrUsername" --password "$acrPassword"

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
